Balaji/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

accounting/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^payins/$',
        view=views.Payins_Index,
        name='Payin_Index'
    ),

    url(
        regex=r'^payins/(?P<id>[0-9]+)/$',
        view=views.Payin_Detail,
        name='Payin_Detail'
        ),
    url(
      regex=r'^payins/add/$',
      view = views.Payin_Add,
      name = 'Payin_Add'
    ),

    url(
      regex=r'^payins/update/(?P<id>[\d]+)/$',
      view = views.Payin_Update,
      name = 'Payin_Update'
    ),

    url(
      regex=r'^payins/delete/(?P<id>[\d]+)/$',
      view = views.Payin_Delete,
      name = 'Payin_Delete'
    ),

    url(
        regex=r'^payouts/$',
        view=views.Payouts_Index,
        name='Payout_Index'
    ),

    url(
        regex=r'^payouts/(?P<id>[0-9]+)/$',
        view=views.Payout_Detail,
        name='Payout_Detail'
        ),
    url(
      regex=r'^payouts/add/$',
      view = views.Payout_Add,
      name = 'Payout_Add'
    ),

    url(
      regex=r'^payouts/update/(?P<id>[\d]+)/$',
      view = views.Payout_Update,
      name = 'Payout_Update'
    ),

    url(
      regex=r'^payouts/delete/(?P<id>[\d]+)/$',
      view = views.Payout_Delete,
      name = 'Payout_Delete'
    ),

    url(
        regex=r'^commissionPayOuts/$',
        view=views.PayCommissionOrSalary_Index,
        name='PayCommissionOrSalary_Index'
        ),
    url(
      regex=r'^commissionPayOuts/add/$',
      view = views.PayCommissionOrSalary_Add,
      name = 'PayCommissionOrSalary_Add'
    ),

    url(
      regex=r'^commissionPayOuts/update/(?P<id>[\d]+)/$',
      view = views.PayCommissionOrSalary_Update,
      name = 'PayCommissionOrSalary_Update'
    ),

    url(
        regex=r'^commissionPayOuts/(?P<id>[0-9]+)/$',
        view=views.PayCommissionOrSalary_Detail,
        name='PayCommissionOrSalary_Detail'
        ),

    url(
      regex=r'^commissionPayOuts/delete/(?P<id>[\d]+)/$',
      view = views.PayCommissionOrSalary_Delete,
      name = 'PayCommissionOrSalary_Delete'
    ),

    url(
        regex=r'invoices/$',
        view=views.Invoice_Index,
        name = 'Invoice_Index'
        ),

    url(
        regex=r'invoices/update/(?P<id>[\d]+)/$',
        view=views.Invoice_Update,
        name = 'Invoice_Update'
        ),

    url(
        regex=r'invoices/delete/(?P<id>[\d]+)/$',
        view=views.Invoice_Delete,
        name = 'Invoice_Delete'
        ),

    url(
        regex=r'bills/$',
        view=views.Bill_Index,
        name = 'Bill_Index'
        ),

    url(
        regex=r'bills/update/(?P<id>[\d]+)/$',
        view=views.Bill_Update,
        name = 'Bill_Update'
        ),

    url(
        regex=r'bills/delete/(?P<id>[\d]+)/$',
        view=views.Bill_Delete,
        name = 'Bill_Delete'
        ),

    url(
        regex=r'commissions/$',
        view=views.Commission_Index,
        name = 'Commission_Index'
        ),

    url(
        regex=r'commissions/add/$',
        view=views.Commission_Add,
        name = 'Commission_Add'
        ),

    url(
        regex=r'commissions/update/(?P<id>[\d]+)/$',
        view=views.Commission_Update,
        name = 'Commission_Update'
        ),

    url(
        regex=r'commissions/delete/(?P<id>[\d]+)/$',
        view=views.Commission_Delete,
        name = 'Commission_Delete'
        ),
    url(
        regex=r'^commissionStructure/$',
        view=views.CommissionStructureIndexView.as_view(),
        name='CommissionStructure_Index'
    ),

    url(
      regex=r'^commissionStructure/add/$',
      view = views.CommissionStructureCreateView.as_view(),
      name = 'CommissionStructure_Add'
    ),

    url(
      regex=r'^commissionStructure/update/(?P<pk>[\d]+)/$',
      view = views.CommissionStructureUpdateView.as_view(),
      name = 'CommissionStructure_Update'
    ),

    url(
      regex=r'^commissionStructure/delete/(?P<pk>[\d]+)/$',
      view = views.CommissionStructureDeleteView.as_view(),
      name = 'CommissionStructure_Delete'
    ),


]

booking/urls.py
from django.conf.urls import url

from .views import *
from . import views


urlpatterns = [
    url(
        regex=r'^events/$',
        view=EventIndexView.as_view(),
        name='Event_Index'
    ),

    url(
      regex=r'^event/(?P<pk>[\d]+)/$',
      view = EventDetailView.as_view(),
      name = 'Event_Detail'
    ),

    url(
      regex=r'^event/add/$',
      view = EventCreateView.as_view(),
      name = 'Event_Create'
    ),

    url(
      regex=r'^event/update/(?P<pk>[\d]+)/$',
      view = EventUpdateView.as_view(),
      name = 'Event_Update'
    ),

    url(
      regex=r'^event/delete/(?P<pk>[\d]+)/$',
      view = EventDeleteView.as_view(),
      name = 'Event_Delete'
    ),

    url(
        regex=r'^booked_services$',
        view=views.Booked_Service_Index,
        name='Booked_Service_Index'
    ),

    url(
    	regex=r'^booking/add/$',
    	view =views.Booked_Service_Add,
    	name='Booked_Service_Add'
    ),
    url(
        regex=r'^booking/update/(?P<id>[0-9]+)/$',
        view=views.Booked_Service_Update,
        name='Booked_Service_Update'
    ),
    url(
        regex=r'^booking/detail/(?P<id>[0-9]+)/$',
        view=views.Booked_Service_Detail,
        name='Booked_Service_Detail'
    ),

    url(
        regex=r'^booking/delete/(?P<id>[0-9]+)/$',
        view=views.Booked_Service_Delete,
        name='Booked_Service_Delete'
    ),

    ]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('Balaji.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^accounting/', include('accounting.urls', namespace='accounting')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

customers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.Index,
        name='index'
    ),

    url(
    	regex=r'^add/$',
    	view =views.Add_Customer,
    	name='add'
    ),
    url(
        regex=r'^update/(?P<id>[0-9]+)/$',
        view=views.Update_Customer,
        name='update'
    ),
    url(
        regex=r'^detail/(?P<id>[0-9]+)/$',
        view=views.Detail_Customer,
        name='detail'
    ),

    url(
        regex=r'^delete/(?P<id>[0-9]+)/$',
        view=views.Delete_Customer,
        name='delete'
    ),

    url(
        regex=r'^vendors/$',
        view=views.Vendor_Index,
        name='vendors'
    ),

    url(
        regex=r'^addVendor/$',
        view =views.Add_Vendor,
        name='addVendor'
    ),

    url(
        regex=r'^updateVendor/(?P<id>[0-9]+)/$',
        view=views.Update_Vendor,
        name='updateVendor'
    ),

    url(
        regex=r'^detailVendor/(?P<id>[0-9]+)/$',
        view=views.Detail_Vendor,
        name='detailVendor'
    ),

     url(
        regex=r'^deleteVendor/(?P<id>[0-9]+)/$',
        view=views.Delete_Vendor,
        name='deleteVendor'
    ),

      url(
         regex=r'^staff/$',
         view=views.StaffIndexView.as_view(),
         name='Staff_Index'
     ),
     url(
       regex=r'^staff/(?P<pk>[\d]+)/$',
       view = views.StaffDetailView.as_view(),
       name = 'Staff_Detail'
     ),
     url(
       regex=r'^staff/add/$',
       view = views.StaffCreateView.as_view(),
       name = 'Staff_Create'
     ),
     url(
       regex=r'^staff/update/(?P<pk>[\d]+)/$',
       view = views.StaffUpdateView.as_view(),
       name = 'Staff_Update'
     ),
     url(
       regex=r'^staff/delete/(?P<pk>[\d]+)/$',
       view = views.StaffDeleteView.as_view(),
       name = 'Staff_Delete'
     ),
]

products/urls.py
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(
        regex=r'^categories/$',
        view=CategoryIndexView.as_view(),
        name='Category_Index'
    ),

    url(
      regex=r'^category/(?P<pk>[\d]+)/$',
      view = CategoryDetailView.as_view(),
      name = 'Category_Detail'
    ),

    url(
      regex=r'^category/add/$',
      view = CategoryCreateView.as_view(),
      name = 'Category_Create'
    ),

    url(
      regex=r'^category/update/(?P<pk>[\d]+)/$',
      view = CategoryUpdateView.as_view(),
      name = 'Category_Update'
    ),

    url(
      regex=r'^category/delete/(?P<pk>[\d]+)/$',
      view = CategoryDeleteView.as_view(),
      name = 'Category_Delete'
    ),

    url(
        regex=r'^products/$',
        view=ProductIndexView.as_view(),
        name='Product_Index'
    ),

    url(
      regex=r'^product/(?P<pk>[\d]+)/$',
      view = ProductDetailView.as_view(),
      name = 'Product_Detail'
    ),

    url(
      regex=r'^product/add/$',
      view = ProductCreateView.as_view(),
      name = 'Product_Create'
    ),

    url(
      regex=r'^product/update/(?P<pk>[\d]+)/$',
      view = ProductUpdateView.as_view(),
      name = 'Product_Update'
    ),

    url(
      regex=r'^product/delete/(?P<pk>[\d]+)/$',
      view = ProductDeleteView.as_view(),
      name = 'Product_Delete'
    ),

    url(
        regex=r'^services/$',
        view=ServiceIndexView.as_view(),
        name='Service_Index'
    ),

    url(
      regex=r'^service/(?P<pk>[\d]+)/$',
      view = ServiceDetailView.as_view(),
      name = 'Service_Detail'
    ),

    url(
      regex=r'^service/add/$',
      view = ServiceCreateView.as_view(),
      name = 'Service_Create'
    ),

    url(
      regex=r'^service/update/(?P<pk>[\d]+)/$',
      view = ServiceUpdateView.as_view(),
      name = 'Service_Update'
    ),

    url(
      regex=r'^service/delete/(?P<pk>[\d]+)/$',
      view = ServiceDeleteView.as_view(),
      name = 'Service_Delete'  
    ),

]

Balaji/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

Balaji/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

Balaji/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

Balaji/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Balaji{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

    {% block additionalcss %}
    {% endblock %}

  </head>

  <body height: 100%;>


      <nav class="navbar  navbar-dark bg-primary navbar-expand-lg ">
    <a class="navbar-brand" href="/">Balaji</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            People
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'customers:index' %}">Customers</a>
            <a class="dropdown-item" href="{% url 'customers:vendors' %}">Vendors</a>
            <a class="dropdown-item" href="{% url 'customers:Staff_Index' %}">Staff</a>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Booking
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'booking:Event_Index' %}">Events</a>
            <a class="dropdown-item" href="{% url 'booking:Booked_Service_Index' %}">Services</a>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Accounting
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounting:Invoice_Index' %}">Invoices</a>
            <a class="dropdown-item" href="{% url 'accounting:Bill_Index' %}">Bills</a>
            <a class="dropdown-item" href="{% url 'accounting:Commission_Index' %}">Commissions</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounting:Payin_Index' %}">Payins</a>
            <a class="dropdown-item" href="{% url 'accounting:Payout_Index' %}">Payouts</a>
            <a class="dropdown-item" href="{% url 'accounting:PayCommissionOrSalary_Index' %}">Commission Payouts</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounting:CommissionStructure_Index' %}">Commission Structure</a>
          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Products
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'products:Category_Index' %}">Categories</a>
            <a class="dropdown-item" href="{% url 'products:Service_Index' %}">Services</a>
            <a class="dropdown-item" href="{% url 'products:Product_Index' %}">Products</a>
          </div>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/admin/">Admin</a>
        </li>
        {% endif %}
      </ul>

      {% if request.user.is_authenticated %}
        <div class=" justify-content-end" >
          <ul class="navbar-nav">
            <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                  </li>
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a class="nav-link " href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                  </li>
          </ul>
        </div>

      {% else %}
        <div class=" justify-content-end" >
          <ul class="navbar-nav ">
              <li class="nav-item ">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a  class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            </ul>





          </div>
      {% endif %}

  </nav>



    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://use.fontawesome.com/640bd40708.js"></script>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}

    {% block additionaljs %}

    {% endblock %}

<br>
<br>

{% block footer %}

{% endblock %}


  </body>



</html>

Balaji/templates/temp.html
<nav class="navbar navbar-toggleable-md navbar-light container " style="background-color: #e3f2fd;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'home' %}">Balaji</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>

      {% if request.user.is_superuser %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'customers:index' %}">Customers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'customers:vendors' %}">Vendors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'products:Category_Index' %}">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/admin/">Admin</a>
      </li>



    </ul>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</li>
    </ul>
      {% endif %}
      {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
      <ul class="navbar-nav">
        <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link " href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
      </ul>
</div>

      {% else %}
        <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
      <ul class="navbar-nav">
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            </ul>
</div>
      {% endif %}

  </div>
</nav>