config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('Balaji.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^accounting/', include('accounting.urls', namespace='accounting')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

customers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.Index,
        name='index'
    ),

    url(
    	regex=r'^add/$',
    	view =views.Add_Customer,
    	name='add'
    ),
    url(
        regex=r'^update/(?P<id>[0-9]+)/$',
        view=views.Update_Customer,
        name='update'
    ),
    url(
        regex=r'^detail/(?P<id>[0-9]+)/$',
        view=views.Detail_Customer,
        name='detail'
    ),

    url(
        regex=r'^delete/(?P<id>[0-9]+)/$',
        view=views.Delete_Customer,
        name='delete'
    ),

    url(
        regex=r'^vendors/$',
        view=views.Vendor_Index,
        name='vendors'
    ),

    url(
        regex=r'^addVendor/$',
        view =views.Add_Vendor,
        name='addVendor'
    ),

    url(
        regex=r'^updateVendor/(?P<id>[0-9]+)/$',
        view=views.Update_Vendor,
        name='updateVendor'
    ),

    url(
        regex=r'^detailVendor/(?P<id>[0-9]+)/$',
        view=views.Detail_Vendor,
        name='detailVendor'
    ),

     url(
        regex=r'^deleteVendor/(?P<id>[0-9]+)/$',
        view=views.Delete_Vendor,
        name='deleteVendor'
    ),

      url(
         regex=r'^staff/$',
         view=views.StaffIndexView.as_view(),
         name='Staff_Index'
     ),
     url(
       regex=r'^staff/(?P<pk>[\d]+)/$',
       view = views.StaffDetailView.as_view(),
       name = 'Staff_Detail'
     ),
     url(
       regex=r'^staff/add/$',
       view = views.StaffCreateView.as_view(),
       name = 'Staff_Create'
     ),
     url(
       regex=r'^staff/update/(?P<pk>[\d]+)/$',
       view = views.StaffUpdateView.as_view(),
       name = 'Staff_Update'
     ),
     url(
       regex=r'^staff/delete/(?P<pk>[\d]+)/$',
       view = views.StaffDeleteView.as_view(),
       name = 'Staff_Delete'
     ),
]

customers/models.py
from __future__ import unicode_literals

from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from core.models import BaseEntity
from Balaji.users.models import User
# Create your models here.
class Customer(BaseEntity):
	"""docstring for Customer"""

	user = models.OneToOneField(
			User,
			blank = True,
			null = True
		)
	name = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='name should contain only alphabets',
				code='invalid_name'
			),
		]
	)
	address = models.CharField(max_length=80)
	city = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='city should contain only alphabets',
				code='invalid_city'
			),
		]
	)
	phone_number = models.CharField(
		max_length=13,
		validators=[
        RegexValidator(
            regex='^[0-9]{10}$',
            message='Phone number should contain only 10 numbers',
			code='invalid Phone number'
			),
    	]
	)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return self.name




class Vendor(BaseEntity):
	"""docstring for Vendor"""

	user = models.OneToOneField(
			User,
			blank = True,
			null = True
		)
	name = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='name should contain only alphabets',
				code='invalid_name'
			),
		]
	)
	address = models.CharField(max_length=80)
	city = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='city should contain only alphabets',
				code='invalid_city'
			),
		]
	)
	phone_number = models.CharField(
		max_length=13,
		validators=[
        RegexValidator(
            regex='^[0-9]{10}$',
            message='Phone number should contain only 10 numbers',
			code='invalid Phone number'
			),
    	]
	)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return self.name

class Staff(BaseEntity):
	"""docstring for Staff"""

	user = models.OneToOneField(
			User,
			blank = True,
			null = True
		)
	name = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='name should contain only alphabets',
				code='invalid_name'
			),
		]
	)
	address = models.CharField(max_length=80)
	city = models.CharField(
		max_length=80,
		validators=[
			RegexValidator(
            	regex='^[a-zA-Z\s]*$',
             	message='city should contain only alphabets',
				code='invalid_city'
			),
		]
	)
	phone_number = models.CharField(
		max_length=13,
		validators=[
        RegexValidator(
            regex='^[0-9]{10}$',
            message='Phone number should contain only 10 numbers',
			code='invalid Phone number'
			),
    	]
	)
	is_active = models.BooleanField(default=True)

	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse('customers:Staff_Detail', kwargs={'pk': self.id})

	def get_update_url(self):
		return reverse('customers:Staff_Update', kwargs={'pk': self.id})

	def get_delete_url(self):
		return reverse('customers:Staff_Delete', kwargs={'pk': self.id})

customers/forms.py
from django import forms

from crispy_forms.helper import FormHelper

from .models import Customer,Vendor

class CustomerForm(forms.ModelForm):
	"""docstring for CustomerForm"""
	
	helper = FormHelper()
	helper.form_tag = False
	helper.form_style = 'inline'
	

	class Meta:
		model = Customer
		exclude = ['user',]
		

class VendorForm(forms.ModelForm):
	"""docstring for CustomerForm"""
	
	helper = FormHelper()
	helper.form_tag = False
	helper.form_style = 'inline'


	class Meta:
		model = Vendor
		exclude = ['user',]
		

customers/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import DetailView
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.urlresolvers import reverse
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin

from .models import Customer, Vendor, Staff
from .forms import CustomerForm, VendorForm
from accounting.forms import CommissionStructureForm
# Create your views here.


def Permission_Check(user):

	return 'customer management' in [i.name for i in user.groups.all()]


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Index(request):
	customers = Customer.objects.all()
	return render(request, 'customers/index.html',{'customers':customers})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Add_Customer(request):
	if request.method == 'POST':
		form = CustomerForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('customers:index'))
	else:
		form = CustomerForm()
	return render(request, 'customers/add.html',{'form':form})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Update_Customer(request,id):
	customer = get_object_or_404(Customer,pk=id)
	form = CustomerForm(request.POST or None,instance = customer)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('customers:index'))
	return render(request, 'customers/update.html',{'form':form, 'id':customer.id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Detail_Customer(request, id):
	customer = get_object_or_404(Customer,pk=id)
	return render(request, 'customers/detail.html', {'customer': customer})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Delete_Customer(request,id):
	customer = get_object_or_404(Customer,pk=id)

	if request.method == 'POST':
		form = CustomerForm(request.POST or None, instance=customer)

		if form.is_valid():
			customer.delete()
			return HttpResponseRedirect(reverse('customers:index'))
	else:
		form = CustomerForm(instance = customer)
	return render(request, 'customers/delete.html', {'form': form, 'id':id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Vendor_Index(request):
	vendors = Vendor.objects.all()
	return render(request, 'vendors/index.html',{'vendors':vendors})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Add_Vendor(request):
	if request.method == 'POST':
		form = VendorForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('customers:vendors'))
	else:
		form = VendorForm()
	return render(request, 'vendors/add.html',{'form':form})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Update_Vendor(request,id):
	vendor = get_object_or_404(Vendor,pk=id)
	form = VendorForm(request.POST or None,instance = vendor)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('customers:vendors'))
	return render(request, 'vendors/update.html',{'form':form, 'id':id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Detail_Vendor(request, id):
	vendor = get_object_or_404(Vendor,pk=id)
	return render(request, 'vendors/detail.html', {'vendor': vendor})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Delete_Vendor(request,id):
	vendor = get_object_or_404(Vendor,pk=id)

	if request.method == 'POST':
		form = VendorForm(request.POST or None, instance=vendor)

		if form.is_valid():
			vendor.delete()
			return HttpResponseRedirect(reverse('customers:vendors'))
	else:
		form = VendorForm(instance = vendor)
	return render(request, 'vendors/delete.html', {'form': form, 'id':id})

class StaffIndexView(LoginRequiredMixin,UserPassesTestMixin,generic.ListView):
    model = Staff
    template_name = 'staff/staff_list.html'
    context_object_name = 'staff_list'
    login_url ='/'

    def test_func(self):
        return  'staff management' in [i.name for i in self.request.user.groups.all()]

class StaffDetailView(LoginRequiredMixin,UserPassesTestMixin,generic.DetailView):
    model = Staff
    template_name = 'staff/staff_detail.html'
    context_object_name = 'staff'
    login_url = '/'

    def test_func(self):
        return  'staff management' in [i.name for i in self.request.user.groups.all()]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        csf = CommissionStructureForm(initial = {'staff':self.object})
        context['CSF'] = csf
        return context


class StaffCreateView(LoginRequiredMixin, UserPassesTestMixin,generic.edit.CreateView):

    model = Staff
    fields = ['name','address','city','phone_number','is_active']
    template_name = 'staff/staff_add.html'
    login_url = '/'

    def test_func(self):
    	return  'staff management' in [i.name for i in self.request.user.groups.all()]

    def get_success_url(self):
        return reverse('customers:Staff_Index')

    def test_func(self):
        print (self.request.user.groups.all())
        return  'staff management' in [i.name for i in self.request.user.groups.all()]

class StaffUpdateView(LoginRequiredMixin,UserPassesTestMixin,generic.edit.UpdateView):
    model = Staff
    fields = ['name','address','city','phone_number','is_active']
    template_name = 'staff/staff_update.html'
    login_url = '/'

    def test_func(self):
        return  'staff management' in [i.name for i in self.request.user.groups.all()]

class StaffDeleteView(LoginRequiredMixin,UserPassesTestMixin,generic.edit.DeleteView):
    model = Staff
    template_name = 'staff/staff_delete.html'
    success_url = reverse_lazy('customers:Staff_Index')
    login_url = '/'

    def test_func(self):
        return  'staff management' in [i.name for i in self.request.user.groups.all()]

customers/templates/vendors/add.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Add Vendor

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Add Vendor</h2>
     <form action="." method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Submit" class="btn btn-primary">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>
      
    </div>
  </div>


</div>
{% endblock content %}

customers/templates/vendors/delete.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Vendor-{{vendor.name}}

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Delete Vendor </h2>
     <form action="{% url 'customers:deleteVendor' id %}"method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Delete" class="btn btn-danger">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>
      
    </div>

</div>
{% endblock content %}

customers/templates/vendors/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Vendor-{{vendor.name}}

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{vendor.name}}</h2>
      <a href="{% url 'customers:updateVendor' vendor.id %}"><button class="btn btn-primary">Update</button></a>
      <a href="{% url 'customers:deleteVendor' vendor.id %}"><button class="btn btn-primary">Delete</button></a> 
    </div>
  </div>


</div>
{% endblock content %}

customers/templates/vendors/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Vendors

{% endblock %}

{% block additionalcss %}
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>list of vendors</h2>
      <br/>
      <a href="{% url 'customers:addVendor' %}"><button type="button" class="btn btn-primary ">Add Vendor</button></a>
      <hr/>


 <table id="vendorsTable" class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>City</th>
      <th>Phone Number</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for v in vendors %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url 'customers:detailVendor' v.id %}">{{ v.name }}</a></td>
      <td>{{ v.city }}</td>
      <td>{{ v.phone_number }}</td>
      <td><a href="{% url 'customers:deleteVendor' v.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
  </div>


</div>
{% endblock content %}


{% block additionaljs %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<script type="text/javascript">
$(document).ready( function () {
    $('#vendorsTable').DataTable();
} );
</script>

{% endblock %}

customers/templates/vendors/update.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Update Vendor

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Update Vendor</h2>
     <form action="{% url 'customers:updateVendor' id %}"method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Submit" class="btn btn-primary">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>
      
    </div>
  </div>


</div>
{% endblock content %}