accounting/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^payins/$',
        view=views.Payins_Index,
        name='Payin_Index'
    ),

    url(
        regex=r'^payins/(?P<id>[0-9]+)/$',
        view=views.Payin_Detail,
        name='Payin_Detail'
        ),
    url(
      regex=r'^payins/add/$',
      view = views.Payin_Add,
      name = 'Payin_Add'
    ),

    url(
      regex=r'^payins/update/(?P<id>[\d]+)/$',
      view = views.Payin_Update,
      name = 'Payin_Update'
    ),

    url(
      regex=r'^payins/delete/(?P<id>[\d]+)/$',
      view = views.Payin_Delete,
      name = 'Payin_Delete'
    ),

    url(
        regex=r'^payouts/$',
        view=views.Payouts_Index,
        name='Payout_Index'
    ),

    url(
        regex=r'^payouts/(?P<id>[0-9]+)/$',
        view=views.Payout_Detail,
        name='Payout_Detail'
        ),
    url(
      regex=r'^payouts/add/$',
      view = views.Payout_Add,
      name = 'Payout_Add'
    ),

    url(
      regex=r'^payouts/update/(?P<id>[\d]+)/$',
      view = views.Payout_Update,
      name = 'Payout_Update'
    ),

    url(
      regex=r'^payouts/delete/(?P<id>[\d]+)/$',
      view = views.Payout_Delete,
      name = 'Payout_Delete'
    ),

    url(
        regex=r'^commissionPayOuts/$',
        view=views.PayCommissionOrSalary_Index,
        name='PayCommissionOrSalary_Index'
        ),
    url(
      regex=r'^commissionPayOuts/add/$',
      view = views.PayCommissionOrSalary_Add,
      name = 'PayCommissionOrSalary_Add'
    ),

    url(
      regex=r'^commissionPayOuts/update/(?P<id>[\d]+)/$',
      view = views.PayCommissionOrSalary_Update,
      name = 'PayCommissionOrSalary_Update'
    ),

    url(
        regex=r'^commissionPayOuts/(?P<id>[0-9]+)/$',
        view=views.PayCommissionOrSalary_Detail,
        name='PayCommissionOrSalary_Detail'
        ),

    url(
      regex=r'^commissionPayOuts/delete/(?P<id>[\d]+)/$',
      view = views.PayCommissionOrSalary_Delete,
      name = 'PayCommissionOrSalary_Delete'
    ),

    url(
        regex=r'invoices/$',
        view=views.Invoice_Index,
        name = 'Invoice_Index'
        ),

    url(
        regex=r'invoices/update/(?P<id>[\d]+)/$',
        view=views.Invoice_Update,
        name = 'Invoice_Update'
        ),

    url(
        regex=r'invoices/delete/(?P<id>[\d]+)/$',
        view=views.Invoice_Delete,
        name = 'Invoice_Delete'
        ),

    url(
        regex=r'bills/$',
        view=views.Bill_Index,
        name = 'Bill_Index'
        ),

    url(
        regex=r'bills/update/(?P<id>[\d]+)/$',
        view=views.Bill_Update,
        name = 'Bill_Update'
        ),

    url(
        regex=r'bills/delete/(?P<id>[\d]+)/$',
        view=views.Bill_Delete,
        name = 'Bill_Delete'
        ),

    url(
        regex=r'commissions/$',
        view=views.Commission_Index,
        name = 'Commission_Index'
        ),

    url(
        regex=r'commissions/add/$',
        view=views.Commission_Add,
        name = 'Commission_Add'
        ),

    url(
        regex=r'commissions/update/(?P<id>[\d]+)/$',
        view=views.Commission_Update,
        name = 'Commission_Update'
        ),

    url(
        regex=r'commissions/delete/(?P<id>[\d]+)/$',
        view=views.Commission_Delete,
        name = 'Commission_Delete'
        ),
    url(
        regex=r'^commissionStructure/$',
        view=views.CommissionStructureIndexView.as_view(),
        name='CommissionStructure_Index'
    ),

    url(
      regex=r'^commissionStructure/add/$',
      view = views.CommissionStructureCreateView.as_view(),
      name = 'CommissionStructure_Add'
    ),

    url(
      regex=r'^commissionStructure/update/(?P<pk>[\d]+)/$',
      view = views.CommissionStructureUpdateView.as_view(),
      name = 'CommissionStructure_Update'
    ),

    url(
      regex=r'^commissionStructure/delete/(?P<pk>[\d]+)/$',
      view = views.CommissionStructureDeleteView.as_view(),
      name = 'CommissionStructure_Delete'
    ),


]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('Balaji.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^accounting/', include('accounting.urls', namespace='accounting')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

accounting/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.urlresolvers import reverse
from django.urls import reverse_lazy
from django.db.models import F
from django.views import generic
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.utils import timezone

from .models import Payin, Invoice, Commission, PayCommissionOrSalary, Bill,CommissionStructure, Payout
from .forms import PayinForm, PayCommissionOrSalaryForm, CommissionForm, InvoiceForm, BillForm, PayoutForm
from booking.models import Event


def Permission_Check(user):

	return 'accounting management' in [i.name for i in user.groups.all()]

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Payins_Index(request):
    payins = Payin.objects.all()
    return render(request,'payins/Payin_Index.html', {'payins_list':payins})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Payin_Add(request):
	if request.method == 'POST':
		form = PayinForm(request.POST)
		if form.is_valid():
			payin = form.save()
			event = Event.objects.get(pk = payin.event.id )
			if event.status != 'COMPLETED':
				event.advance = event.advance + payin.amount
				event.save()
			return HttpResponseRedirect(reverse('booking:Event_Detail', kwargs={'pk':payin.event.id}))
	else:
		form = PayinForm(initial = {'date':timezone.now().date(), 'time': timezone.now().time()})
	return render(request, 'payins/Payin_Add.html',{'form':form})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Payin_Update(request,id):
	payin = get_object_or_404(Payin,pk=id)
	form = PayinForm(request.POST or None,instance = payin)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('accounting:Payin_Index'))
	return render(request, 'payins/Payin_Update.html',{'form':form, 'id':payin.id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Payin_Detail(request, id):
	payin = get_object_or_404(Payin,pk=id)
	return render(request, 'payins/Payin_Detail.html', {'payin': payin})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Payin_Delete(request,id):
	payin = get_object_or_404(Payin,pk=id)

	if request.method == 'POST':
		form = PayinForm(request.POST or None, instance=payin)

		if form.is_valid():
			payin.delete()
			return HttpResponseRedirect(reverse('accounting:Payin_Index'))
	else:
		form = PayinForm(instance = payin)
	return render(request, 'payins/Payin_Delete.html', {'form': form, 'id':id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def PayCommissionOrSalary_Index(request):
    payouts = PayCommissionOrSalary.objects.all()
    return render(request,'payouts_commission/Payout_Commission_Index.html', {'payouts_list':payouts})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def PayCommissionOrSalary_Add(request):
	if request.method == 'POST':
		form = PayCommissionOrSalaryForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('accounting:PayCommissionOrSalary_Index'))
	else:
		form = PayCommissionOrSalaryForm(initial = {'date':timezone.now().date(), 'time': timezone.now().time()})
	return render(request, 'payouts_commission/Payout_Commission_Add.html',{'form':form})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def PayCommissionOrSalary_Update(request,id):
	payout = get_object_or_404(PayCommissionOrSalary,pk=id)
	form = PayCommissionOrSalaryForm(request.POST or None,instance = payout)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('accounting:PayCommissionOrSalary_Index'))
	return render(request, 'payouts_commission/Payout_Commission_Update.html',{'form':form, 'id':payout.id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def PayCommissionOrSalary_Detail(request, id):
	payout = get_object_or_404(PayCommissionOrSalary,pk=id)
	return render(request, 'payouts_commission/Payout_Commission_Detail.html', {'payout': payout})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def PayCommissionOrSalary_Delete(request,id):
	payout = get_object_or_404(PayCommissionOrSalary,pk=id)

	if request.method == 'POST':
		form = PayCommissionOrSalaryForm(request.POST or None, instance=payout)

		if form.is_valid():
			payout.delete()
			return HttpResponseRedirect(reverse('accounting:PayCommissionOrSalary_Index'))
	else:
		form = PayCommissionOrSalaryForm(instance = payout)
	return render(request, 'payouts_commission/Payout_Commission_Delete.html', {'form': form, 'id':id})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Invoice_Index(request):
	invoices = Invoice.objects.all().annotate(due_amount =F('amount') - F('paid'))
	return render(request,'invoices/invoices_index.html', {'invoices':invoices})



@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Invoice_Update(request, id):
	invoice = get_object_or_404(Invoice,pk=id)
	form = InvoiceForm(request.POST or None, instance = invoice)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('accounting:Invoice_Index'))
	return render(request, 'invoices/invoicess_update.html', {'form':form, 'id':invoice.id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Invoice_Delete(request,id):
	invoice = get_object_or_404(Invoice,pk=id)

	if request.method == 'POST':
		form = InvoiceForm(request.POST or None, instance=invoice)

		if form.is_valid():
			invoice.delete()
			return HttpResponseRedirect(reverse('accounting:Invoice_Index'))
	else:
		form = InvoiceForm(instance = invoice)
	return render(request, 'invoices/invoices_delte.html', {'form': form, 'id':id})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Commission_Index(request):
	commissions = Commission.objects.all().annotate(due_amount =F('amount') - F('paid'))
	return render(request, 'commissions/commissions_index.html', {'commissions': commissions})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Commission_Add(request):
	if request.method == 'POST':
		form = CommissionForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('accounting:Commission_Index'))
	else:
		form = CommissionForm()
	return render(request, 'commissions/commissions_add.html',{'form':form})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Commission_Update(request, id):
	commission = get_object_or_404(Commission,pk=id)
	form = CommissionForm(request.POST or None, instance = commission)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('accounting:Commission_Index'))
	return render(request, 'commissions/commissions_update.html', {'form':form, 'id':commission.id})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Commission_Delete(request,id):
	commission = get_object_or_404(Commission,pk=id)

	if request.method == 'POST':
		form = CommissionForm(request.POST or None, instance=commission)

		if form.is_valid():
			commission.delete()
			return HttpResponseRedirect(reverse('accounting:Commission_Index'))
	else:
		form = CommissionForm(instance = commission)
	return render(request, 'commissions/commissions_delte.html', {'form': form, 'id':id})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Bill_Index(request):
	bills = Bill.objects.all()
	return render(request, 'bills/bills_index.html', {'bills': bills})


@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Bill_Update(request, id):
	bill = get_object_or_404(Bill,pk=id)
	form = BillForm(request.POST or None, instance = bill)
	if form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('accounting:Bill_Index'))
	return render(request, 'bills/bills_update.html', {'form':form, 'id':bill.id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Bill_Delete(request, id):
	bill = get_object_or_404(Bill,pk=id)

	if request.method == 'POST':
		form = BillForm(request.POST or None, instance=bill)

		if form.is_valid():
			bill.delete()
			return HttpResponseRedirect(reverse('accounting:Bill_Index'))
	else:
		form = BillForm(instance = bill)
	return render(request, 'bills/bills_delte.html', {'form': form, 'id':id})


class CommissionStructureIndexView(LoginRequiredMixin,UserPassesTestMixin,generic.ListView):
    model = CommissionStructure
    template_name = 'CommissionStructure/CommissionStructure_list.html'
    context_object_name = 'CommissionStructure_list'
    login_url = '/'

    def test_func(self):
        return  'accounting management' in [i.name for i in self.request.user.groups.all()]


class CommissionStructureCreateView(LoginRequiredMixin, UserPassesTestMixin,generic.edit.CreateView):
    model = CommissionStructure
    fields = ['staff', 'service','amount']
    template_name = 'CommissionStructure/CommissionStructure_add.html'
    login_url = '/'

    def test_func(self):
        return  'accounting management' in [i.name for i in self.request.user.groups.all()]

    def get_success_url(self):
        return reverse('customers:Staff_Detail', kwargs={'pk':self.object.staff.id})


class CommissionStructureUpdateView(LoginRequiredMixin,UserPassesTestMixin,generic.edit.UpdateView):
    model = CommissionStructure
    fields = ['staff', 'service','amount']
    template_name = 'CommissionStructure/CommissionStructure_update.html'
    login_url = '/'

    def test_func(self):
        return  'accounting management' in [i.name for i in self.request.user.groups.all()]

accounting/templates/commissions/commissions_add.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Add Commission

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Add Commission</h2>
     <form class="form-horizontal" method="post" action="{% url 'accounting:Commission_Add' %}">
    	{% csrf_token %}
    	{{ form|crispy }}
    	<div class="control-group">
      		<div class="controls">
    			<input type="submit" value="Submit" class="btn btn-primary">
    			<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
    		</div>
    	</div>
	</form>


    </div>
  </div>


</div>
{% endblock content %}

accounting/templates/commissions/commissions_delte.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Commission-{{commission.staff}}

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Delete Commission</h2>
     <form action="{% url 'accounting:Commission_Delete' id %}"method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Delete" class="btn btn-danger">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>

    </div>

</div>
{% endblock content %}

accounting/templates/commissions/commissions_index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Commissions

{% endblock %}

{% block additionalcss %}
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>list of Commissions</h2>
      <br>
      <a href="{% url 'accounting:Commission_Add' %}"><button type="button" class="btn btn-primary">Add Commission</button></a>
      <hr/>

 <table id="commissionsTable" class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Staff Name</th>
      <th>Created Date</th>
      <th>Due Date</th>
      <th>Paid Date</th>
      <th>Status</th>
      <th>Total Amount</th>
      <th>Paid Amount</th>
      <th>Due Amount</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for i in commissions %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td> {{ i.staff}}</td>
      <td>{{ i.generated_date }}</td>
      <td>{{ i.due_date }}</td>
      <td>{{ i.paid_date }}</td>
      <td>{{ i.status }}</td>
      <td>{{ i.amount }}</td>
      <td>{{ i.paid }}</td>
      <td>{{ i.due_amount }}</td>
      <td><a href="{{ i.get_update_url }}"><button type="button" class="btn btn-primary" name="button">Edit</button></a></td>
      <td><a href="{{ i.get_delete_url }}"><button type="button" class="btn btn-danger" name="button">Delete</button></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
  </div>


</div>
{% endblock content %}


{% block additionaljs %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<script type="text/javascript">
$(document).ready( function () {
    $('#commissionsTable').DataTable();
} );
</script>

{% endblock %}

accounting/templates/commissions/commissions_update.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Update Commission

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Update Commission</h2>
     <form action="{% url 'accounting:Commission_Update' id %}"method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Submit" class="btn btn-primary">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>

    </div>
  </div>


</div>
{% endblock content %}

accounting/templates/commissions/invoices_index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Invoices

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>list of Invoices</h2>


 <table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Customer Name</th>
      <th>Created Date</th>
      <th>Due Date</th>
      <th>Status</th>
      <th>Total Amount</th>
      <th>Paid Amount</th>
      <th>Due Amount<th>
    </tr>
  </thead>
  <tbody>
  {% for i in invoices %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td> {{ i.customer}}</td>
      <td>{{ i.generated_date }}</td>
      <td>{{ i.due_date }}</td>
      <td>{{ i.status }}</td>
      <td>{{ i.amount }}</td>
      <td>{{ i.paid }}</td>
      <td>{{ i.due_amount }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
  </div>


</div>
{% endblock content %}