booking/urls.py
from django.conf.urls import url

from .views import *
from . import views


urlpatterns = [
    url(
        regex=r'^events/$',
        view=EventIndexView.as_view(),
        name='Event_Index'
    ),

    url(
      regex=r'^event/(?P<pk>[\d]+)/$',
      view = EventDetailView.as_view(),
      name = 'Event_Detail'
    ),

    url(
      regex=r'^event/add/$',
      view = EventCreateView.as_view(),
      name = 'Event_Create'
    ),

    url(
      regex=r'^event/update/(?P<pk>[\d]+)/$',
      view = EventUpdateView.as_view(),
      name = 'Event_Update'
    ),

    url(
      regex=r'^event/delete/(?P<pk>[\d]+)/$',
      view = EventDeleteView.as_view(),
      name = 'Event_Delete'
    ),

    url(
        regex=r'^booked_services$',
        view=views.Booked_Service_Index,
        name='Booked_Service_Index'
    ),

    url(
    	regex=r'^booking/add/$',
    	view =views.Booked_Service_Add,
    	name='Booked_Service_Add'
    ),
    url(
        regex=r'^booking/update/(?P<id>[0-9]+)/$',
        view=views.Booked_Service_Update,
        name='Booked_Service_Update'
    ),
    url(
        regex=r'^booking/detail/(?P<id>[0-9]+)/$',
        view=views.Booked_Service_Detail,
        name='Booked_Service_Detail'
    ),

    url(
        regex=r'^booking/delete/(?P<id>[0-9]+)/$',
        view=views.Booked_Service_Delete,
        name='Booked_Service_Delete'
    ),

    ]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('Balaji.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^accounting/', include('accounting.urls', namespace='accounting')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

booking/forms.py
from django import forms
from django.db.models import Q

from crispy_forms.helper import FormHelper

from .models import Booked_Service, Event


class DateInput(forms.DateInput):
	input_type = 'date'


class Booked_Service_Form(forms.ModelForm):
	"""form for Booked_Service"""

	helper = FormHelper()
	helper.form_tag = False
	helper.form_style = 'inline'


	class Meta:
		model = Booked_Service
		exclude = ['']
		widgets = {
			'start_date' : DateInput(),
			'end_date' : DateInput(),
		}

	def __init__(self, *args, **kwargs):
		super(Booked_Service_Form, self).__init__(*args, **kwargs)
		self.fields['event'].queryset = Event.objects.filter(~Q(status='COMPLETED'))


class EventForm(forms.ModelForm):
	"""form for Event"""

	helper = FormHelper()
	helper.form_tag = False
	helper.form_style = 'inline'

	class Meta:
		model = Event
		exclude = ['']
		widgets = {
			'start_date' : DateInput(),
			'end_date' : DateInput(),
		}

booking/views.py
from django.core.urlresolvers import reverse
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic import DetailView
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils import timezone

from .models import Event,Booked_Service
from .forms import Booked_Service_Form, EventForm
from accounting.forms import PayinForm


class EventIndexView(LoginRequiredMixin,UserPassesTestMixin,generic.ListView):
    model = Event
    template_name = 'booking/event_list.html'
    context_object_name = 'events_list'
    login_url = '/'

    def test_func(self):
        return  'event management' in [i.name for i in self.request.user.groups.all()]


class EventDetailView(LoginRequiredMixin,UserPassesTestMixin,generic.DetailView):
    model = Event
    template_name = 'booking/event_detail.html'
    context_object_name = 'event'
    login_url = '/'

    def test_func(self):
        return  'event management' in [i.name for i in self.request.user.groups.all()]

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # add booked service form
        bsf = Booked_Service_Form(
                initial = {'event':self.object,
                            'start_date':self.object.start_date,
                            'start_time': self.object.start_time,
                            'end_date':self.object.end_date,
                            'end_time':self.object.end_time
                           }
                )
        try:
            amt= self.object.invoice.all()[0].amount - self.object.invoice.all()[0].paid
        except:
            amt = 0
        pf = PayinForm(initial = {
                'event':self.object,
                'customer':self.object.customer,
                'date':timezone.now().date(),
                'time':timezone.now().time(),
                'amount': amt
                })

        context['booked_service_form'] = bsf
        context['Payin_form'] = pf
        return context


class EventCreateView(LoginRequiredMixin, UserPassesTestMixin,generic.edit.CreateView):
    model = Event
    form_class = EventForm
    template_name = 'booking/event_add.html'
    login_url = '/'

    def test_func(self):
        return  'event management' in [i.name for i in self.request.user.groups.all()]

    def get_success_url(self):
        return reverse('booking:Event_Index')

    def test_func(self):
        print (self.request.user.groups.all())
        return  'event management' in [i.name for i in self.request.user.groups.all()]


class EventUpdateView(LoginRequiredMixin,UserPassesTestMixin,generic.edit.UpdateView):
    model = Event
    form_class = EventForm
    template_name = 'booking/event_update.html'
    login_url = '/'

    def test_func(self):
        return  'event management' in [i.name for i in self.request.user.groups.all()]

class EventDeleteView(LoginRequiredMixin,UserPassesTestMixin,generic.edit.DeleteView):
    model = Event
    template_name = 'booking/event_delete.html'
    success_url = reverse_lazy('booking:Event_Index')
    login_url = '/'

    def test_func(self):
        return  'event management' in [i.name for i in self.request.user.groups.all()]


def Permission_Check(user):

	return 'event management' in [i.name for i in user.groups.all()]

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Booked_Service_Index(request):
	booked_services = Booked_Service.objects.all()
	return render(request, 'booked_services/booked_services_list.html',{'booked_services':booked_services})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Booked_Service_Add(request):
	if request.method == 'POST':
		form = Booked_Service_Form(request.POST)
		if form.is_valid():
			service = form.save()
			return HttpResponseRedirect(reverse('booking:Event_Detail', kwargs={'pk':service.event.id}))
	else:
		form = Booked_Service_Form()
	return render(request, 'booked_services/booked_services_add.html',{'form':form})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Booked_Service_Update(request,id):
	booked_service = get_object_or_404(Booked_Service,pk=id)
	form = Booked_Service_Form(request.POST or None,instance = booked_service)
	if form.is_valid():
		service = form.save()
		return HttpResponseRedirect(reverse('booking:Event_Detail', kwargs={'pk':service.event.id}))
	return render(request, 'booked_services/booked_services_update.html',{'form':form, 'id':booked_service.id})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Booked_Service_Detail(request, id):
    booked_service= get_object_or_404(Booked_Service,pk=id)
    return render(request, 'booked_services/booked_services_detail.html', {'booked_service': booked_service})

@login_required
@user_passes_test(Permission_Check,redirect_field_name= None)
def Booked_Service_Delete(request,id):
	booked_service = get_object_or_404(Booked_Service,pk=id)

	if request.method == 'POST':
		form = Booked_Service_Form(request.POST or None, instance=booked_service)

		if form.is_valid():
			booked_service.delete()
			return HttpResponseRedirect(reverse('booking:Booked_Service_Index'))
	else:
		form = Booked_Service_Form(instance = booked_service)
	return render(request, 'booked_services/booked_service_delete.html', {'form': form, 'id':id})

booking/templates/booked_services/booked_service_delete.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Booking Service-{{ booking_service }}

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Delete Booked Service</h2>
     <form action="{% url 'booking:Booked_Service_Delete' id %}"method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Delete" class="btn btn-danger">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>

    </div>

</div>
{% endblock content %}

booking/templates/booked_services/booked_services_add.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Add Booked Service

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Add Booked Service</h2>
     <form action="." method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Submit" class="btn btn-primary">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>

    </div>
  </div>


</div>
{% endblock content %}

booking/templates/booked_services/booked_services_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Booked Service-{{ booked_service.event }}

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ booked_service.event }}</h2>
      <a href="{% url 'booking:Booked_Service_Update' booked_service.id %}"><button class="btn btn-primary">Update</button></a>
      <a href="{% url 'booking:Booked_Service_Delete' booked_service.id %}"><button class="btn btn-primary">Delete</button></a>
    </div>
  </div>


</div>
{% endblock content %}

booking/templates/booked_services/booked_services_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}

Services

{% endblock %}

{% block additionalcss %}
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>list of Services served</h2>
      <br/>
      <a href="{% url 'booking:Booked_Service_Add' %}"><button type="button" class="btn btn-primary">Add Booking Service</button></a>
      <hr/>
{% if booked_services %}
 <table id="servicesTable" class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Event</th>
      <th>Service</th>
      <th>start_date</th>
      <th>start_time</th>
      <th>end_date</th>
      <th>end_time</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Vendor</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for c in booked_services %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url 'booking:Booked_Service_Detail' c.id %}">{{ c.event }}</a></td>
      <td>{{ c.service }}</td>
      <td>{{ c.start_date }}</td>
      <td>{{ c.start_time }}</td>
      <td>{{ c.end_date }}</td>
      <td>{{ c.end_time }}</td>
      <td>{{ c.quantity }}</td>
      <td>{{ c.price }}</td>
      <td>{{ c.vendor }}</td>
      <td><a href="{% url 'booking:Booked_Service_Delete' c.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<h3>No Booked Services yet, Would you like to add one </h3>
{% endif %}
    </div>
  </div>


</div>
{% endblock content %}


{% block additionaljs %}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
<script type="text/javascript">
$(document).ready( function () {
    $('#servicesTable').DataTable();
} );
</script>

{% endblock %}

booking/templates/booked_services/booked_services_update.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}

Update Booked Service

{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>Update Booked Service</h2>
     <form action="{% url 'booking:Booked_Service_Update' id %}"method="POST">
    	{% csrf_token %}
    	{% crispy form %}
    	<input type="submit" value="Submit" class="btn btn-primary">
    	<a href="{{ request.META.HTTP_REFERER }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
	</form>

    </div>
  </div>


</div>
{% endblock content %}